---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main


jobs:

  test:
    name: Test-Before-Proceeding
    runs-on: ununtu-latest


    steps:
      - name: Test Syntax
        run: |
          ansible-playbook main-test.yml --syntax-check
